name: "Prepare Configuration"
description: "Prepare Configuration"

inputs:
  gitops_repo:
    descriptions: "Param#1"
    required: true
  gitops_manage_branch:
    descriptions: "Param#2"
    required: true
  gitops_token:
    descriptions: "Param#3"
    required: true
  gitops_app_name: 
    descriptions: "Param#4"
    required: true
  sourcecode_manage_branch: 
    descriptions: "Param#5"
    required: true
  github_token: 
    descriptions: "Param#6"
    required: true
    
outputs:
  pom_app_version:
    description: "version number from pom.xml"
    value: ${{ steps.pom_dat.outputs.version }}
  pom_app_name:
    description: "version number from pom.xml"
    value: ${{ steps.pom_dat.outputs.name }}
    
runs:
  using: "composite"
  steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2.4.0
      with:        
        ref: ${{ inputs.sourcecode_manage_branch }}
        path: project_src
        
    - name: Check Source Code
      shell: bash
      run: |
        echo "Check Source Code"
        cd project_src
        pwd
        ls -l
  
    #- name: Checkout Source Code
    #  run: |
    #      git clone https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@${{ env.GITLAB_REPO }}
    #      cd ${{ env.SOURCECODE_HOME_PATH }}
    #      git switch ${{ env.SOURCECODE_MANAGE_BRANCH }}
    
    - name: Get version
      id: pom_dat
      shell: bash
      run: |
          echo "Get version"
          cd project_src
          POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          POM_NAME=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)
          echo "::set-output name=version::$POM_VERSION"
          echo "::set-output name=name::$POM_NAME"
          echo "POM_APP_VERSION=$POM_VERSION" > ../version_control.txt     
          echo "POM_APP_NAME=$POM_NAME" >> ../version_control.txt
 
      - name: Upload version artifact
        uses: actions/upload-artifact@v1
        with:
          name: version
          path: version_control.txt   
