name: "Prepare Configuration"
description: "Prepare Configuration"

inputs:
  gitops_repo:
    descriptions: "Param#1"
    required: true
  gitops_manage_branch:
    descriptions: "Param#2"
    required: true
  gitops_token:
    descriptions: "Param#3"
    required: true
  gitops_app_name: 
    descriptions: "Param#4"
    required: true
    
    
runs:
  using: "composite"
  steps:
    - name: Checkout GitOps Repo
      uses: actions/checkout@v2.4.0
      with:
        repository: ${{ inputs.gitops_repo }}
        ref: ${{ inputs.gitops_manage_branch }}
        token: ${{ inputs.gitops_token }}
        path: manage_gitops
      
    - name: Geneate new Build Number
      shell: bash
      id: version
      run: |
          cd manage_gitops/${{ inputs.gitops_app_name }}
          cur_build_number=$(cat version_control.txt|grep '^BUILD_VERSION'|awk -F'=' '{print($2)}')
          echo "cur_build_number=${cur_build_number}"
          ((new_build_number=cur_build_number+1))
          echo "new_build_number=${new_build_number}"
          #echo "BUILD_VERSION=${new_build_number}" > version_control.txt
          #echo "BUILD_VERSION=${new_build_number} " >> $GITHUB_ENV
          echo "::set-output name=BUILD_VERSION::${new_build_number}"     
      
