name: "Prepare Configuration"
description: "Prepare Configuration"

inputs:
  gitops_repo:
    descriptions: "Param#1"
    required: true
  gitops_manage_branch:
    descriptions: "Param#2"
    required: true
  gitops_token:
    descriptions: "Param#3"
    required: true
  gitops_app_name: 
    descriptions: "Param#4"
    required: true
  sourcecode_manage_branch: 
    descriptions: "Param#5"
    required: true
    
    
runs:
  using: "composite"
  steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2.4.0
      with:        
        ref: ${{ inputs.sourcecode_manage_branch }}
        path: project_src
        
    - name: Check Source Code
      shell: bash
      run: |
        cd project_src
        pwd
        ls -l
  
    #- name: Checkout Source Code
    #  run: |
    #      git clone https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@${{ env.GITLAB_REPO }}
    #      cd ${{ env.SOURCECODE_HOME_PATH }}
    #      git switch ${{ env.SOURCECODE_MANAGE_BRANCH }}
    
    - name: Get POM Version
      uses: avides/actions-project-version-check@latest
      id: actions_project_version_check
      with:
        token: ${{ inputs.gitops_token }}
        file-to-check: project_src/pom.xml

    - name: use-version-from-check
      shell: bash
      run: echo "New version is: " ${{ steps.actions_project_version_check.outputs.version }}



