name: "Build Container"
description: "Build Container"

inputs:
  sourcecode_manage_branch: 
    descriptions: "Project source code repository branch"
    required: false
    default: develop
  sourcecode_home_path: 
    descriptions: "Source Code Home Path"
    required: false
    default: project_src
  github_token: 
    descriptions: "GitHub PAT"
    required: true
  acr_registry_server: 
    descriptions: "ACR Registry Server"
    required: false
    default: gableesaving.azurecr.io
  acr_user: 
    descriptions: "ACR Login User"
    required: false
    default: gableesaving    
  acr_password: 
    descriptions: "ACR Login password"
    required: true
    
    
#outputs:
#  pom_app_version:
#    description: "version number from pom.xml"
#    value: ${{ steps.pom_dat.outputs.version }}
#  pom_app_name:
#    description: "version number from pom.xml"
#    value: ${{ steps.pom_dat.outputs.name }}
    
runs:
  using: "composite"
  steps:        
    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
          login-server: ${{ inputs.acr_registry_server }}
          username: ${{ inputs.acr_user }}
          password: ${{ inputs.acr_password }}

    - name: Build and Push Container Image (ACR)
      shell: bash
      run: |
          echo "Build and Push Container Image (ACR)"      
          cd ${{ inputs.sourcecode_home_path }}
          ls -l
          docker build . -t ${{ inputs.acr_registry_server }}/${{env.APP_NAME}}:${{env.IMAGE_VERSION}}
          docker push ${{ inputs.acr_registry_server }}/${{env.APP_NAME}}:${{env.IMAGE_VERSION}}
          
    - name: Security Scan Container Image (Anchore)
      uses: anchore/scan-action@b08527d5ae7f7dc76f9621edb6e49eaf47933ccd
      with:
        image: "${{ inputs.acr_registry_server }}/${{env.APP_NAME}}:${{env.IMAGE_VERSION}}"
        # Generate a SARIF report and set the `sarif` output parameter after successful action execution.  This report is compatible with GitHub Automated Code Scanning (ACS), as the artifact to upload for display as a Code Scanning Alert report.
        acs-report-enable: true
        # Set this to any value to enable verbose debug output
        #debug: # optional, default is false
        # Set to false to avoid failing based on severity-cutoff. Default is to fail when severity-cutoff is reached (or surpassed)
        fail-build: false # optional, default is true      
        # Optionally specify the minimum vulnerability severity to trigger an "error" level ACS result.  Valid choices are "negligible", "low", "medium", "high" and "critical".  Any vulnerability with a severity less than this value will lead to a "warning" result.  Default is "medium".
        #severity-cutoff: critical # optional, default is medium (critical)

    - name: Upload Container Image Scan Report (Anchore)
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif

