name: "Notification"
description: "Notification"

inputs:
  notify_token: 
    descriptions: "Notify Token"
    required: false
    default: 01415c3ad9dc5cde2f3dd5cde9d005f5cd2c6be5
  notify_mesg: 
    descriptions: "Notify Message"
    required: true
    
   
runs:
  using: "composite"
  steps:
    - name: Notification
      shell: bash
      run: |
        echo "Notification : ${{inputs.notify_mesg}}"
       
  

