name: "Setup Variable Configuration"
description: "Setup Variable Configuration"

inputs:
  github_token: 
    descriptions: "GitHub PAT"
    required: true
  gitops_repo:
    descriptions: "GitOps Repository in GitHub"
    required: false
    default: 'e-saving/gitops_deployment'
  gitops_manage_branch:
    descriptions: "GitOps Repository Branch"
    required: false
    default: 'master'
  gitops_token:
    descriptions: "GitOps Repository PAT"
    required: true
    
runs:
  using: "composite"
  steps:

    - run: echo "STEP_NAME=Checkout GitOps Repo" >> $GITHUB_ENV
      shell: bash

    - name: Checkout GitOps Repo
      uses: actions/checkout@v2.4.0
      with:
        repository: ${{ inputs.gitops_repo }}
        ref: ${{ inputs.gitops_manage_branch }}
        token: ${{ inputs.gitops_token }}
        path: manage_gitops       

    - run: echo "STEP_NAME=Setup Variables" >> $GITHUB_ENV
      shell: bash
    
    - name: Setup Variables
      shell: bash
      run: |
          echo "Setup Variables"
          cd manage_gitops/environment/develop
          cat variable.properties | while read line
          do
            echo "${line}" >> ${GITHUB_ENV}            
          done
          echo "gitops_repo=${{ inputs.gitops_repo }}" >> ${GITHUB_ENV}  
          echo "gitops_manage_branch=${{ inputs.gitops_manage_branch }}" >> ${GITHUB_ENV}
    
    - name: "Failure Notification" 
      uses: e-saving/birdtest-template-cicd/Dev/NotificationAction@main
      if: ${{ failure() }}
      with:
        github_token: ${{ inputs.github_token }}
        notify_mesg: "Setup Variable Configuration Failure at step ${{ env.STEP_NAME }}"
          
