name: "Code Quality Scan"
description: "Code Quality Scan"

inputs:
  sourcecode_manage_branch: 
    descriptions: "Project source code repository branch"
    required: false
    default: develop
  sourcecode_home_path: 
    descriptions: "Source Code Home Path"
    required: false
    default: project_src    
  github_token: 
    descriptions: "GitHub PAT"
    required: true
  sonar_host_url: 
    descriptions: "SonarQube Host URL"
    required: false
    default: http://20.187.187.182:9000/
  sonar_token: 
    descriptions: "SonarQube Token"
    required: false
    default: 01415c3ad9dc5cde2f3dd5cde9d005f5cd2c6be5

   
runs:
  using: "composite"
  steps:
    - name: Scan Source Code Quality (SonarQube)
      shell: bash
      run: |
          echo "Scan Source Code Quality (SonarQube)"          
          cd ${{ inputs.sourcecode_home_path }}
          mvn sonar:sonar -Dsonar.projectKey=${{env.APP_NAME}} -Dsonar.host.url=${{ inputs.sonar_host_url }} -Dsonar.login=${{ inputs.sonar_token }}
      
    - name: Check Code Quality Gate (SonarQube)
      uses: SonarSource/sonarqube-quality-gate-action@v1.0.0
      #timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ inputs.sonar_token }}
      with:
        scanMetadataReportFile: ${{ inputs.sourcecode_home_path }}/target/sonar/report-task.txt

