name: "Update and Commit Deployment Configuration"
description: "Update and Commit Deployment Configuration"

inputs:
  github_token: 
    descriptions: "GitHub PAT"
    required: true
  gitops_token:
    descriptions: "GitOps Repository PAT"
    required: true
  sourcecode_home_path: 
    descriptions: "Source Code Home Path"
    required: false
    default: project_src

   
runs:
  using: "composite"
  steps:
  
    - run: echo "STEP_NAME=Commit pom.xml files" >> $GITHUB_ENV
      shell: bash  
  
    - name: Commit pom.xml files
      shell: bash
      run: |
        cd ${{ inputs.sourcecode_home_path }}
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pom.xml        
        git commit -m "[ci-skip] update pom.xml new version to be ${{ env.POM_VERSION }}"
        git tag ${{ env.POM_VERSION }}
        
    - run: echo "STEP_NAME=Push pom.xml changes" >> $GITHUB_ENV
      shell: bash          
          
    - name: Push pom.xml changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ env.sourcecode_manage_branch }}
        directory: ${{ inputs.sourcecode_home_path }}
        #tags: xxx

    - run: echo "STEP_NAME=Commit and push version control file (GitOps Repo)" >> $GITHUB_ENV
      shell: bash
      
    - run: echo "GITOPS_MANAGE_HOME_PATH=${{ env.APP_NAME }}" >> $GITHUB_ENV
      shell: bash

    - name: Commit and push version control file (GitOps Repo)
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ inputs.gitops_token }}
      with:
        source_file: version/version_control.txt
        destination_repo: ${{ env.gitops_repo }}
        destination_folder: ${{ env.GITOPS_MANAGE_HOME_PATH }}
        destination_branch: ${{ env.gitops_manage_branch }}
        user_email: 'github_actions@g-able.com'
        user_name: 'github_actions'
        commit_message: 'Update new container image version ${{ env.IMAGE_VERSION }} of ${{ env.GITOPS_MANAGE_HOME_PATH }}/version_control.txt'          
        
    - run: echo "STEP_NAME=Commit and push deployment configuration (Helm)" >> $GITHUB_ENV
      shell: bash        
          
    - name: Commit and push deployment configuration (Helm)
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
         API_TOKEN_GITHUB: ${{ inputs.gitops_token }}
      with:
         source_file: version/values.yaml
         destination_repo: ${{ env.gitops_repo }}
         destination_folder: ${{ env.GITOPS_MANAGE_HOME_PATH }}
         destination_branch: ${{ env.gitops_manage_branch }}
         user_email: 'github_actions@g-able.com'
         user_name: 'github_actions'
         commit_message: 'Update new container image version ${{ env.IMAGE_VERSION }} of ${{ env.GITOPS_MANAGE_HOME_PATH }}/values.yaml'
         
    - name: "Failure Notification" 
      uses: e-saving/birdtest-template-cicd/Dev/NotificationAction@main
      if: ${{ failure() }}
      with:
        github_token: ${{ inputs.github_token }}
        notify_mesg: "Update and Commit Deployment Configuration Failure at step ${{ env.STEP_NAME }}"
          
