name: "Build Container"
description: "Build Container"

inputs:
  sourcecode_manage_branch: 
    descriptions: "Project source code repository branch"
    required: false
    default: develop
  github_token: 
    descriptions: "GitHub PAT"
    required: true    
    
#outputs:
#  pom_app_version:
#    description: "version number from pom.xml"
#    value: ${{ steps.pom_dat.outputs.version }}
#  pom_app_name:
#    description: "version number from pom.xml"
#    value: ${{ steps.pom_dat.outputs.name }}
    
runs:
  using: "composite"
  steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2.4.0
      with:        
        ref: ${{ inputs.sourcecode_manage_branch }}
        path: project_src
        
    #- name: Checkout Source Code
    #  run: |
    #      git clone https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@${{ env.GITLAB_REPO }}
    #      cd ${{ env.SOURCECODE_HOME_PATH }}
    #      git switch ${{ env.SOURCECODE_MANAGE_BRANCH }}
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Download version artifact
      uses: actions/download-artifact@v1
      with:
        name: version

    - name: Check version number
      shell: bash
      run: |
        echo "Check version number"
        img_version=$(cat version/version_control.txt|grep '^IMAGE_VERSION'|awk -F'=' '{print($2)}')
        app_name=$(cat version/version_control.txt|grep '^APP_NAME'|awk -F'=' '{print($2)}')
        echo "IMAGE_VERSION=${img_version}" >> $GITHUB_ENV
        echo "APP_NAME=${app_name}" >> $GITHUB_ENV
        
    - name: Build and Unit Testing with Maven
      shell: bash
      run: |
          echo "Build and Unit Testing with Maven"
          cd project_src
          if [[ -d badges ]]
          then
            rm -Rf badges
          fi
          mkdir -p badges
          ls -l
          #mvn package -Pcoverage
          java -version
          mvn clean
          mvn package
          ls -l target/
          ls -l target/site/jacoco/
            
    - name: Generate Unit Test Result (JaCoCo)
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: project_src/badges
        jacoco-csv-file: project_src/target/site/jacoco/jacoco.csv
        generate-branches-badge: true
        generate-summary: true
           
    - name: Upload Unit Test Coverage Report (JaCoCo)
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-report
        path: project_src/target/site/jacoco/
        
    - name: GitHub Push      
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ inputs.github_token }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: # optional, default is 
        # Destination branch to push changes
        branch: ${{ inputs.sourcecode_manage_branch }}
        # Determines if force push is used
        #force: # optional
        # Determines if --tags is used
        #tags: # optional
        # Directory to change to before pushing.
        directory: project_src/badges

