name: "Build Test Source Code"
description: "Build Test Source Code"

inputs:
  sourcecode_manage_branch: 
    descriptions: "Project source code repository branch"
    required: false
    default: develop
  sourcecode_home_path: 
    descriptions: "Source Code Home Path"
    required: false
    default: project_src
  github_token: 
    descriptions: "GitHub PAT"
    required: true
    
runs:
  using: "composite"
  steps:
    
    - run: echo "STEP_NAME=Download version artifact" >> $GITHUB_ENV
      shell: bash

    - name: Download version artifact
      uses: actions/download-artifact@v1
      with:
        name: version
        
    - run: echo "STEP_NAME=Build and Unit Testing with Maven" >> $GITHUB_ENV
      shell: bash
        
    - name: Build and Unit Testing with Maven
      shell: bash
      run: |
          echo "Build and Unit Testing with Maven"          
          cd ${{ inputs.sourcecode_home_path }}
          if [[ -d badges ]]
          then
            rm -Rf badges
          fi
          mkdir -p badges
          ls -l
          #mvn package -Pcoverage
          java -version
          mvn clean
          mvn package
          ls -l target/
          ls -l target/site/jacoco/
          
    - run: echo "STEP_NAME=Generate Unit Test Result (JaCoCo)" >> $GITHUB_ENV
      shell: bash
            
    - name: Generate Unit Test Result (JaCoCo)
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: ${{ inputs.sourcecode_home_path }}/badges
        jacoco-csv-file: ${{ inputs.sourcecode_home_path }}/target/site/jacoco/jacoco.csv
        generate-branches-badge: true
        generate-summary: true
        
    - run: echo "STEP_NAME=Upload Unit Test Coverage Report (JaCoCo)" >> $GITHUB_ENV
      shell: bash
           
    - name: Upload Unit Test Coverage Report (JaCoCo)
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-report
        path: ${{ inputs.sourcecode_home_path }}/target/site/jacoco/
        
    - run: echo "STEP_NAME=GitHub Push Badges " >> $GITHUB_ENV
      shell: bash
        
    - name: GitHub Push Badges     
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ inputs.github_token }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: # optional, default is 
        # Destination branch to push changes
        branch: ${{ inputs.sourcecode_manage_branch }}
        # Determines if force push is used
        #force: # optional
        # Determines if --tags is used
        #tags: # optional
        # Directory to change to before pushing.
        directory: ${{ inputs.sourcecode_home_path }}/badges
        
        
    - name: "Failure Notification" 
      uses: e-saving/birdtest-template-cicd/Dev/NotificationAction@main
      if: ${{ failure() }}
      with:
        github_token: ${{ inputs.github_token }}
        notify_mesg: "Build Test Source Code Failure at step ${{ env.STEP_NAME }}"
